version: '3'
services:
    web:
        image: nginx
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - "86:80"
        networks:
            - test2_laravel
        depends_on:
            - frontend
            - php-fpm

    php-fpm:
        build: ./docker
        volumes:
            - '.:/var/www/html'
            - './docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
        networks:
            - test2_laravel

    db:
        image: postgres:14.1
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        #        volumes:
        #            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "54326:5432"
        networks:
            - test2_laravel

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        working_dir: /app
        command: /bin/sh -c "npm install && npm start"
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        networks:
            - test2_laravel

networks:
    test2_laravel:
        driver: bridge